### PR TITLE
(Bug #728) Changed the upstart script to run on login i

### PR DESCRIPTION
**Pull request by RabidArts**
... instead of startup - to fix issues when using profiles with no auto-login

For more information, please see https://github.com/xbianonpi/xbian/issues/728

### CODE REVIEW

**Comment by RabidArts** [comment]
Investigating improved solution, as previous solution had knock-on effects (forcing 2x login)

**Comment by mk01** [comment]
@RabidArts 

the needed "initctl emit xbmc-loaded" was moved directly into xbmc code, so non starting of this service (without login - in case of profiles) should not longer be an issue. or ?

**Comment by RabidArts** [comment]
Wasn't aware of the move of the init - if you're comfortable that this resolve it, then cool.
Will give it a try ;)

**Comment by mk01** [comment]
sure! report back

**Pull request closed without merging**
